### ISSUE TITLE
SLI menu/metric libraries terminology

### ISSUE THREAD

**Issue by laurahiles** [HO-CTO/sre-monitoring-as-code#54]
It would be good to use consistent terminology for the SLI menu/metric libraries:

In Overview > How MaC Works: change "MaC contains configuration libraries..." to "MaC contains metric libraries (Service-level indicator menu)..." with a link to Service-level indicator menu.

**Comment by michaelpearsonHO** [comment]
Soon to be addressed as part of other tickets.
