### ISSUE TITLE
Links to internal confluence architecture information

### ISSUE THREAD

**Issue by laurahiles** [HO-CTO/sre-monitoring-as-code#55]
In 'Interpret MaC outputs', search for "Most of the labels are outlined in Designing Service Alerting”. There are couple of sections that have placeholder NOTE text. This information is currently in internal documentation, it will need to be decided where this info is kept and how it's best presented in the external docs.

**Comment by michaelpearsonHO** [comment]
Pending work on SEGAS Public Docs-as-Code site.
